### ISSUE TITLE
v1.18: Using net/http handlers aswell in framework

### ISSUE THREAD

**Issue by apoorvcodes** [gominima/minima#41]
**Is your feature request related to a problem? Please describe.**
]The problem is some people are not willing to switch to minima handlers so we need to add support of net/http standard handlers

**Describe the solution you'd like**
A good solution would be moving to go 1.18 and using generics and allowing to take both minima handlers and net/http as logic handlers for the route and appending them on basis of the type using reflect

**Describe alternatives you've considered**
A good alternative can be a stand alone router for net/http something like https://github.com/gominima/router.

**Comment by apoorvcodes** [comment]
@booleanrecep @savioxavier What are ur thoughts on this

**Comment by apoorvcodes** [comment]
@megatank58 whats ur take on this

**Comment by megatank58** [comment]
This seems like the best choice, however we would need to update the docgen to the v1.18 syntax before doing this, which won't take much time after the docgen cleanup so it will be followup. Overall we should give this a shot

**Comment by booleanrecep** [comment]
> @booleanrecep @savioxavier What are ur thoughts on this

My knowledge is limited on that topic for now actually. If I come across any good solution I ll offer.

**Comment by apoorvcodes** [comment]
So, after all this evaluation I feel we should make it into a separate project which uses net/http handler and it would basically be minima but as a router for net/http rather than framework.

**Comment by megatank58** [comment]
Couldn't the same router have a different function to use net/http handler

**Comment by apoorvcodes** [comment]
Yea

**Comment by apoorvcodes** [comment]
The thing can be done we can use nGet with net/http function, but then it defeats the purpose of the framework, and also lowers the performance
