### ISSUE TITLE
Congratulations and questions

### ISSUE THREAD

**Issue by frederikhors** [gominima/minima#42]
Congratulations for your work.

Can you please add benchmarks?

What do you think about https://bunrouter.uptrace.dev?

**Comment by apoorvcodes** [comment]
Hey there, I have already checked out burnrouter looks very good we were thinking to have something similar like it, and as per benchmarks we haven't done a lot of em, but we use hash-table for the url matching which will be on par with radix tree so basically very performant. We still are in testing and bug fixing stages so expect some problems here and there, Thanks for your interest in gominima

**Comment by apoorvcodes** [comment]
Also if you want benchmarks we are open for a pr for that

**Comment by apoorvcodes** [comment]
Due to no more response closing this issue reopen if more queries! Have a nice day @frederikhors
